name: restaurant_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5
  http: ^1.2.0

 
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.1

  google_sign_in: ^5.4.2
  shared_preferences: ^2.5.3
  introduction_screen: ^4.0.0

  image_picker: ^1.1.2
  intl: ^0.20.2
  cool_nav: ^0.1.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
